BoxLayout:
    orientation: "vertical"
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            on_text: app.convert_unit()
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.handle_increment(1)
            Button:
                text: 'Down'
                on_press: app.handle_increment(-1)
#    Button :
#        text: 'Convert miles to km'
#        on_press: app.convert_unit()
    Label:
        id: output_label